spring:
  application:
    name: logtree-sample
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8084

# LogTree Configuration
logtree:
  enabled: true
  auto-trace-controllers: true
  auto-trace-services: true
  trace-transaction-boundaries: true
  trace-sql-queries: true  # LogTree SQL 로깅 활성화
  sql-query-max-length: 300
  include-headers: false
  exclude-headers:
    - Authorization
    - Cookie
  exclude-urls:
    - /health
    - /actuator/**
  max-depth: 10
  colored-output: true
  log-style: tree

# Logging Configuration
logging:
  level:
    root: INFO
    io.github.logtree: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
  pattern:
    console: "%cyan(%d{HH:mm:ss.SSS}) [%highlight(%-5level)] [%yellow(%15.15t)] [%blue(%X{traceId:-NO_TRACE})] %green(%X{visual:-}) %white(%logger{36}.%M) - %msg%n"